### ISSUE TITLE
Error: cannot create directory "/weechat/.weechat"

### ISSUE THREAD

**Issue by ja-ab** [jkaberg/dockerfiles#1]
This wont run on CentOS 7 with the following error:

# docker run -it --tty --name weechat -v ~/weechat:/weechat jkaberg/weechat 
Error: cannot create directory "/weechat/.weechat"

**Comment by jkaberg** [comment]
Make sure the mounted directory is writeable by UID 1000 and GID 1000 or build the image yourself and change them, https://github.com/jkaberg/dockerfiles/blob/master/weechat/Dockerfile#L5-L6.
